# Actual FROM is provided via command-line flag. See base.ex.
#
# Scratch is only used as a placeholder to avoid the error "stage 1
# requires a FROM instruction".
FROM scratch

RUN microdnf -y install glibc-langpack-en --nodocs --setopt install_weak_deps=False && \
    microdnf -y clean all && \
    echo "LANG=\"en_US.UTF-8\"" > /etc/locale.conf

ENV LANG en_US.UTF-8
