FROM registry.fedoraproject.org/fedora-minimal:42

RUN microdnf -y install glibc-langpack-en --nodocs --setopt install_weak_deps=False && \
    microdnf -y clean all && \
    echo "LANG=\"en_US.UTF-8\"" > /etc/locale.conf

ENV LANG en_US.UTF-8
